/* Auto-generated by prepare_videos.py. Feel free to edit axes/endpoint. */
window.SURVEY_CONFIG = {
  study_id: "cache_accel_test_v1",

  bases: [
    {
        "id": "rolling_forcing",
        "label": "rolling_forcing",
        "prompts": [
            "000_man_made_rocks",
            "001_man_riding_horse",
            "002_push_through_ocean"
        ]
    },
    {
        "id": "self_forcing",
        "label": "self_forcing",
        "prompts": [
            "000_3d_animation_small",
            "001_beautifully_detailed_papercraft",
            "002_macro_shot_focusing"
        ]
    }
],

  ours_id: "ours",
  baselines: ["vanilla", "teacache", "toca", "fast_ar"],

  video_url: "videos/{base}/{prompt}_{method}.mp4",

  prompt_texts: {
    "rolling_forcing/000_man_made_rocks": "A man made of rocks walking in the forest, full-body shot.",
    "rolling_forcing/001_man_riding_horse": "A man riding a horse through the Gobi Desert with a beautiful sunset behind him, movie quality.",
    "rolling_forcing/002_push_through_ocean": "A push through an ocean research outpost.",
    "self_forcing/000_3d_animation_small": "A 3D animation of a small, round, fluffy creature with big, expressive eyes exploring a vibrant, enc",
    "self_forcing/001_beautifully_detailed_papercraft": "A beautifully detailed papercraft illustration of a vibrant coral reef teeming with colorful fish an",
    "self_forcing/002_macro_shot_focusing": "A macro shot focusing on the face of a young woman with freckles, her expression intense as she look"
},

  axes: [
    { id: "overall",  label: "Overall",
      question: "Considering everything, including visual quality and alignment with the prompt, which video is better overall?" },
    { id: "visual",   label: "Visual Quality",
      question: "Which video has better visual quality (sharpness, detail, fewer artifacts)?" },
    { id: "motion",   label: "Motion Quality",
      question: "Which video shows smoother, more natural motion (less flicker or stutter)?" },
    { id: "temporal", label: "Temporal Consistency",
      question: "Which video better maintains its quality and consistency from beginning to end?" }
  ],

  require_full_watch: true,
  endpoint: "https://script.google.com/macros/s/AKfycbz03sS8CK5g3vwPmSzcwjOCA537Wqchv2DOuje2rteNQw2nkbMjU9rwbM02plWQgxwEBA/exec"
};
